### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by Delivator** [krikunts/captionbot#2]
Whenever i create the bot `c = CaptionBot()` or use the bot `c.url_caption('img_url')`,
i get this message:

`/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)`

**Comment by krikunts** [comment]
Unfortunately I had to turn off SSL certificate verification. 
The reason for doing it: when I turn it on I get SSL error:

```
hostname 'www.captionbot.ai' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net'
```

I'm still searching for more clean solution for this.

**Comment by cwliu** [comment]
Have you found a solution for this?

**Comment by krikunts** [comment]
@cwliu Normally I should use certifi package for this, but haven't tried it yet

**Comment by krikunts** [comment]
version 0.1.4 fixes this
